data_fortress_dbt_project:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '/tmp/data_fortress.duckdb'
      filesystems:
        - fs: s3
          anon: false
          key: "{{ env_var('MINIO_ACCESS_KEY') }}"
          secret: "{{ env_var('MINIO_SECRET_KEY') }}"
          client_kwargs:
            endpoint_url: "http://{{ env_var('MINIO_HOST') }}"
      external_root: "s3://raw"
      extensions:
        - parquet
        - spatial